name: 'Release psu to ref'

on:
  workflow_dispatch:
    inputs:
        psuWorkflowRunID:
          description: 'The workflow run id of a psu run to download packaged code from'
          required: true

jobs:
  release_to_ref:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
  
    steps:
      - name: download build artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged_code 
          path: .
          github-token: ${{ secrets.GH_PAT }}
          repository: NHSDigital/eps-prescription-status-update-api
          run-id: ${{ inputs.psuWorkflowRunID }}

      - name: Display structure of downloaded files
        run: ls -R
